### ISSUE TITLE
Plenary document: ToC should not be in bold, etc.

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-unece#3]
As title.

**Comment by ronaldtse** [comment]
In Plenary document:
* There are 2 footnotes numbered as "3".
* UNECE declaration page not needed (after cover page)
* ToC not needed
* Document identifier placed in header should be "ECE/TRADE/C/CEFACT/2018/6" not "Plenary No. GE.18-02016(E)"
* "Box 1" is like a "Figure", it needs a caption of "Box 1: The United Nations Centre for Trade Facilitation and e-Business"
* "Box 1" border should be black
* a bit more vertical space after Table 1.
* list bullets should be indented in, and have some vertical spacing before/after (see below).

<img width="593" alt="screen shot 2018-10-18 at 12 45 45 am" src="https://user-images.githubusercontent.com/11865/47102395-38be5280-d26f-11e8-9a91-788d02ea5fdc.png">

**Comment by opoudjis** [comment]
I inevitably preface this by saying that perpetuating idiosyncratic differences in formatting between Plenary and Recommendations is not doing anyone any favours, and if UNECE actually end up using this in production, they must undertake a review of their formatting conventions.

* ToC no longer in bold.
* Removed ToC from plenary documents.
* Removed UNECE declaration page from plenary documents (unless there is a foreword or introduction)

**Comment by opoudjis** [comment]
> There are 2 footnotes numbered as "3".

Cannot replicate, and indeed, I don't see how that could have happened.

> "Box 1" is like a "Figure", it needs a caption of "Box 1: The United Nations Centre for Trade Facilitation and e-Business"

Right now in the PDF it has an inner caption and an outer caption which are identical. I am not going to replicate that, that is simply a bug; and in the Recommendation, only the inner caption was used. I am treating this as a random inconsistency.

> Document identifier placed in header should be "ECE/TRADE/C/CEFACT/2018/6" not "Plenary No. GE.18-02016(E)"

Done. If this gem ends up used, I will need an explanation of these identifiers.

**Comment by opoudjis** [comment]
> "Box 1" border should be black

Done

> a bit more vertical space after Table 1.

This is a longstanding issue with all gems' Word output, creating new ticket: https://github.com/riboseinc/metanorma-iso/issues/234

> list bullets should be indented in, and have some vertical spacing before/after (see below).

The lack of vertical space between list items is the Word optimisation (`mso-add-space:auto`) that I disabled for ISO, and enabled for all other gems. Disabling for this gem.

All lists indented by an addition 18pt.
