### ISSUE TITLE
HTML Plenary document "Foreword" should be called "Summary" and should not be preceded by empty spaces

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-unece#6]
For Plenary documents, it is "Summary". For a Recommendation, it is "Foreword".

Right now for plenary documents, in Doc it is "Summary".

<img width="816" alt="screen shot 2018-10-23 at 10 52 40 am" src="https://user-images.githubusercontent.com/11865/47332427-d1aafe80-d6b1-11e8-9fb4-010cbcc65008.png">

But in HTML, it is "Foreword", and is also preceded by empty spaces (`&#xA0; Foreword`).

<img width="779" alt="screen shot 2018-10-23 at 10 51 43 am" src="https://user-images.githubusercontent.com/11865/47332419-cd7ee100-d6b1-11e8-8ed5-5e72caa1f41d.png">

**Comment by opoudjis** [comment]
Depends on https://github.com/riboseinc/metanorma-unece/issues/7
