### ISSUE TITLE
Adding the "Note" page to Recommendations

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-unece#8]
In Recommendations, there is an extra page that is not shown in the HTML:

<img width="463" alt="screen shot 2018-10-23 at 12 46 07 pm" src="https://user-images.githubusercontent.com/11865/47336281-a7f9d380-d6c1-11e8-9db6-d500c6e5347b.png">

**Comment by opoudjis** [comment]
None of this was put into the HTML because the HTML output was not in scope at the time.

**Comment by ronaldtse** [comment]
Indeed. Nonetheless, every format we have delivered we have created an HTML page, so we should still complete it.
